### ISSUE TITLE
How do i use this??

### ISSUE THREAD

**Issue by dmvvilela** [devopsfaith/krakend-cors#8]
I'm sorry, but this documentation is horrible..

First of all there are many mistakes here:

Configuration Example
  "extra_config": {
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [ "http://foobar.com" ],
      "allow_methods": [ "POST", "GET"],
      "max_age": "12h"
    }
  }
or leave the defaults (the defaults allows all origins):

"extra_config": {
  github_com/devopsfaith/krakend-metrics": {
    "allow_origins": []
  }
}

krakend metrics?? Missing "?? And also.. this does not work.. what more do i have to do?

I saw gin tests, but it didnt even use extra config from json.. How do i use this middleware????

I tried everything nothing works..

**Comment by alombarte** [comment]
Hi @dmvvilela,

Yes, there's a lot to do on documentation. But le me say that there are two things I mainly enjoy in the morning. One is fresh toasts, and the other is to read comforting issues like yours, full of encouraging words and appreciation of free work.

I am not going to extend myself on your impressive capabilities of cheering the community as you've lost enough time on our software.  Let me answer your questions below.

The first line of this repo says:

> A set of building blocks for instrumenting KrakenD gateways

This repository is one block of the many in KrakenD: CORS. It's meant to be used within the KrakenD ecosystem.

The KrakenD Designer, shows a little bit of the choices you can use here: https://designer.krakend.io/#!/service (make sure to scroll down)

The CORS module can be used with these 3 lines:
https://github.com/devopsfaith/krakend-ce/blob/a331f53087c0f8747b53d5e7fb76bf92ad53c88d/router_engine.go#L19-L21

Additionally, you can check the integration tests for CORS here:
https://github.com/devopsfaith/krakend-ce/tree/6cad2381e10b8f02f0d93cb6b55e68ace7645ad1/tests/fixtures/specs

Finally, if you could point at least one of these many mistakes of this configuration is, we would be very happy so we can report back to the +500 clusters that are using this configuration in production.

**Comment by dmvvilela** [comment]
Well, i think you deserve an apology from me. I was rude, and i am sorry :)
I ended up using the middleware on gin for CORs.

The idea was for a positive feedback on the documentation, i was angry at the time but i agree that we should be more encouraging on this kind of stuff.

For the three lines, i don't know where "cfg config.ServiceConfig" comes from. I know, i am new to this, and the fault is mine for not knowing without "for noobs" docs.

For the mistakes, and did not said it was the code, it was from the initial docs and i will point them here again to help and make my rude comment worth of something:

On readme.md:

Configuration Example
"extra_config": {
"github_com/devopsfaith/krakend-cors": {
"allow_origins": [ "http://foobar.com" ],
"allow_methods": [ "POST", "GET"],
"max_age": "12h"
}
}
or leave the defaults (the defaults allows all origins):

"extra_config": {
github_com/devopsfaith/krakend-metrics": {
"allow_origins": []
}
}

the defaults points to krakend-metrics and not krakend-cors as the above saying do, which may be correct but it seems that is wrong since they do the same stuff.

Also, if you copy and paste it will not work because is missing a  ". I know, it is simple, i should not complain about that.

So i am grateful for the awesome free software and your work! I will keep studying to avoid this kind of noob question.

Please accept this apologies and enjoy your next toasts and morning coffee with a smile!

**Comment by alombarte** [comment]
No problem Daniel, I fixed the Readme with your suggestions. Thanks for pointing it out.

I would recommend diving in the krakend-ce repository and its tests to understand how everything is glued together.
